deneme/Controllers/MessageController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace deneme.Controllers
{
    public class MessageController : Controller
    {
        MessageTwoManager mm=new MessageTwoManager(new EfMessageTwoRepository());
        Context c = new Context();

     
        public IActionResult InBox()
        {
            var username = User.Identity.Name;
            var usermail = c.Users.Where(x => x.UserName == username).
                Select(y => y.Email).FirstOrDefault();
            var writerID = c.Writers.Where(x => x.WriterMail == usermail).
                Select(y => y.WriterID).FirstOrDefault();

            int id = writerID;
            var values=mm.GetInboxListByWriter(id);
            return View(values);
        }

        public IActionResult SendBox()
        {
            var username = User.Identity.Name;
            var usermail = c.Users.Where(x => x.UserName == username).
                Select(y => y.Email).FirstOrDefault();
            var writerID = c.Writers.Where(x => x.WriterMail == usermail).
                Select(y => y.WriterID).FirstOrDefault();

            int id = writerID;
            var values = mm.GetSendboxListByWriter(id);
            return View(values);
        }
       
        [HttpGet]
        public IActionResult MessageDetails(int id)
        {
            var value=mm.TGetById(id);
            return View(value);
        }

        public async Task<List<AppUser>> GetUsersAsync()
        {
            using (var context = new Context())
            {
                return await context.Users.ToListAsync();
            }
        }
        [HttpGet]
        public async Task<IActionResult> SendMessage() 
        {
            //KUllanıcıları DropDown'a Çektiğimiz Alan            
            List<SelectListItem> recieverUsers = (from x in await GetUsersAsync()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.Email.ToString(),
                                                      Value = x.Id.ToString()
                                                  }).ToList();
            //Burası Yukarıde Çektiğimiz Verileri Front-End Tarafına Taşıyoruz.
            ViewBag.RecieverUser = recieverUsers;
            return View(); 
        }
        [HttpPost]
        public IActionResult SendMessage(MessageTwo p)
        {
            var userName = User.Identity.Name;
            var userMail = c.Users.Where(x => x.UserName == userName).Select(y => y.Email).FirstOrDefault();
            var WriterID = c.Writers.Where(x => x.WriterMail == userMail).Select(y => y.WriterID).FirstOrDefault();

            p.SenderID = WriterID;
            p.MessageStatus = true;
            p.MessageDate = DateTime.Now;
            mm.TAdd(p);

            return RedirectToAction("SendBox");

            //var username = User.Identity.Name;
            //var usermail = c.Users.Where(x => x.UserName == username).
            //    Select(y => y.Email).FirstOrDefault();
            //var writerID = c.Writers.Where(x => x.WriterMail == usermail).
            //    Select(y => y.WriterID).FirstOrDefault();
            //p.SenderID= writerID;
            //p.ReceiverID = 2;
            //p.MessageStatus = true;
            //p.MessageDate=Convert.ToDateTime(DateTime.Now.ToShortDateString());
            //mm.TAdd(p);
            //return RedirectToAction("InBox");
        }
    }
}

deneme/Views/Message/InBox.cshtml
@using EntityLayer.Concrete
@model List<MessageTwo>

@{
    ViewData["Title"] = "InBox";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}
<h1>Gelen Kutusu</h1>
@{if (Model.Count!=0)
{
    <table class="table table-bordered">
        <tr>
            <th>#</th>
            <th>Konu</th>
            <th>Gönderen</th>
            <th>Tarih</th>
            <th>Mesajı Aç</th>

        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <th>@item.MessageID</th>
                <td>@item.Subject</td>
                <td>@item.SenderUser.WriterName</td>
                @* <td>@(((DateTime)item.MessageDate).ToString("dd MMM yyyy"))</td>              *@
                @{
                    DateTime messageDate = item.MessageDate;
                    TimeSpan elapsed = DateTime.Now - messageDate;

                    if (elapsed.TotalDays >= 365)
                    {
                        int years = (int)(elapsed.TotalDays / 365);
                        <td>@($"{years} yıl önce")</td>
                    }
                    else if (elapsed.TotalDays >= 30)
                    {
                        int months = (int)(elapsed.TotalDays / 30);
                        <td>@($"{months} ay önce")</td>
                    }
                    else if (elapsed.TotalDays >= 1)
                    {
                        <td>@($"{(int)elapsed.TotalDays} gün önce")</td>
                    }
                    else if (elapsed.TotalHours >= 1)
                    {
                        <td>@($"{(int)elapsed.TotalHours} saat önce")</td>
                    }
                    else
                    {
                        <td>@($"{(int)elapsed.TotalMinutes} dakika önce")</td>
                    }
                }
                <td><a href="/Message/MessageDetails/@item.MessageID" class="btn btn-warning">Mesajı Aç</a></td>
            </tr>
        }
    </table>
    <a href="/Message/SendMessage/" class="btn btn-info">Yeni Mesaj Oluştur</a>
    <a href="/Message/SendBox/" class="btn btn-info">Giden Mesajları Gör</a>
}

}@{else
{
  <h1>Mesajınız Yok</h1>  
}}

deneme/Views/Message/MessageDetails.cshtml
@model EntityLayer.Concrete.MessageTwo
@{
    ViewData["Title"] = "MessageDetails";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Mesaj Detay Sayfası</h1>

@Html.Label("Mesaj ID")
@Html.TextBoxFor(x => x.MessageID, new { @class = "form-control", disabled = "disabled" })
<br />
@Html.Label("Mesaj Başlığ")
@Html.TextBoxFor(x => x.Subject, new { @class = "form-control", disabled = "disabled" })
<br />
@Html.Label("Mesaj İçeriği")
@Html.TextBoxFor(x => x.MessageDetails, new { @class = "form-control", disabled = "disabled" })
<br />
<a href="/Message/InBox/">
    <button class="btn btn-success">Mesajara Dön</button>

</a>

deneme/Views/Message/SendBox.cshtml
@using EntityLayer.Concrete
@model List<MessageTwo>

@{
    ViewData["Title"] = "SendBox";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Giden Kutusu</h1>
@{
    if (Model.Count != 0)
    {
        <table class="table table-bordered">
            <tr>
                <th>#</th>
                <th>Konu</th>
                <th>Alıcı</th>
                <th>Tarih</th>
                <th>Mesajı Aç</th>

            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <th>@item.MessageID</th>
                    <td>@item.Subject</td>
                    <td>@item.ReceiverUser.WriterName</td>
                    @* <td>@(((DateTime)item.MessageDate).ToString("dd MMM yyyy"))</td>              *@
                    @{
                        DateTime messageDate = item.MessageDate;
                        TimeSpan elapsed = DateTime.Now - messageDate;

                        if (elapsed.TotalDays >= 365)
                        {
                            int years = (int)(elapsed.TotalDays / 365);
                            <td>@($"{years} yıl önce")</td>
                        }
                        else if (elapsed.TotalDays >= 30)
                        {
                            int months = (int)(elapsed.TotalDays / 30);
                            <td>@($"{months} ay önce")</td>
                        }
                        else if (elapsed.TotalDays >= 1)
                        {
                            <td>@($"{(int)elapsed.TotalDays} gün önce")</td>
                        }
                        else if (elapsed.TotalHours >= 1)
                        {
                            <td>@($"{(int)elapsed.TotalHours} saat önce")</td>
                        }
                        else
                        {
                            <td>@($"{(int)elapsed.TotalMinutes} dakika önce")</td>
                        }
                    }
                    <td><a href="/Message/MessageDetails/@item.MessageID" class="btn btn-warning">Mesajı Aç</a></td>
                </tr>
            }
        </table>
        <a href="/Message/SendMessage/" class="btn btn-info">Yeni Mesaj Oluştur</a>
    }

}@{
    else
    {
        <h1>Mesajınız Yok</h1>
    }
}

deneme/Views/Message/SendMessage.cshtml
@model EntityLayer.Concrete.MessageTwo
@{
    ViewData["Title"] = "SendMessage";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Yeni Mesaj Oluşturma</h1>
@using (Html.BeginForm("SendMessage", "Message", FormMethod.Post))
{
    @Html.Label("Alıcı")
    @* @Html.TextBoxFor(x => x.Subject, new { @class = "form-control" }) *@
    @Html.DropDownListFor(x => x.ReceiverID, (List<SelectListItem>)ViewBag.RecieverUser, new { @class = "form-control" })
 
    <br />
    @Html.Label("Konu")
    @Html.TextBoxFor(x => x.Subject, new { @class = "form-control" })
    <br />
    @Html.Label("Mesajınız")
    @Html.TextAreaFor(x => x.MessageDetails, 15, 3, new { @class = "form-control" })
    <br />

    <br />
    <button class="btn btn-success">Mesajı Gönder</button>
}